### ISSUE TITLE
Fork of certificate-info for expiry warnings

### ISSUE THREAD

**Issue by kkostrzewa** [blupig/certificate-info#16]
I have forked certificate-info into https://github.com/kkostrzewa/certificate-info to provide some UI around certificates that are nearing expiry 

Details, along with UI can be found in this world readable google doc: https://docs.google.com/document/d/1vVJrZ9d2s9c2qIDEr85Fh5r6ohE8L_rfNDErsDS2hp4/edit

(I am more than happy to copy that into a github artifact in case you'd rather not open that).

Are you interested in incorporating this back into the main branch? I'm happy to work with you on that

**Comment by yunzhu-li** [comment]
Hi Kevin,

Thanks for working on this plugin and letting me know. I took a look at the changes and they look good to me and I'll be happy to incorporate it back and update on Chrome store.

I do have a few questions, would you mind opening a pull request and we can discuss there?

Thanks,
Yunzhu
